// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesMvcAsp.Data;

namespace SalesMvcAsp.Migrations
{
    [DbContext(typeof(SalesMvcAspContext))]
    [Migration("20200524231245_OtherEntitiess")]
    partial class OtherEntitiess
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SalesMvcAsp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("SalesMvcAsp.Models.SallesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("Seller_Id");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("Seller_Id");

                    b.ToTable("SallesRecord");
                });

            modelBuilder.Entity("SalesMvcAsp.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("Department_Id");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Department_Id");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("SalesMvcAsp.Models.SallesRecord", b =>
                {
                    b.HasOne("SalesMvcAsp.Models.Seller", "Seller_")
                        .WithMany()
                        .HasForeignKey("Seller_Id");
                });

            modelBuilder.Entity("SalesMvcAsp.Models.Seller", b =>
                {
                    b.HasOne("SalesMvcAsp.Models.Department", "Department_")
                        .WithMany("Selers")
                        .HasForeignKey("Department_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
